CREATE PROCEDURE CAPNHAT_SLSP
	@MADH NVARCHAR(10),
	@MASP NVARCHAR(10),
	@SLSP BIGINT,
AS
BEGIN
	BEGIN TRAN
		IF NOT EXISTS (SELECT * FROM CHITIETDONHANG WHERE CHITIETDONHANG.MaSP = @MASP AND CHITIETDONHANG.MaDH=@MADH)
		BEGIN
			ROLLBACK
			RAISERROR(N'Chi tiết đơn hàng không tồn tại', 16, 1)
		END
    IF (@SLSP <=0)
    BEGIN
      ROLLBACK
      RAISERROR(N'Số lượng sản phẩm không hợp lệ',16,1)
    END
    
    WAITFOR DELAY '00:00:5'
    UPDATE CHITIETDONHANG 
	  SET SoLuong=@SLSP
    WHERE MaSP = @MASP AND MaDH = @MADH
	COMMIT TRAN
END
GO

EXECUTE CAPNHAT_SLSP @MADH =N'DH0422',
	@MASP = N'SP6293',  
	@SLSP = 5


