CREATE PROCEDURE NHANVIEN_XEM_HOPDONG @MaHD NVARCHAR(10)
BEGIN
	BEGIN TRAN
		SELECT * FROM HOPDONG WHERE HOPDONG.MaHD = @MaHD
		WAITFOR DELAY '00:00:10'
		SELECT * FROM HOPDONG WHERE HOPDONG.MaHD = @MaHD
	COMMIT TRAN
END
GO

EXEC NHANVIEN_XEM_HOPDONG @MaHD = N'HD0000'
GO
